name: CallCoreDemo
on:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Start background process
      run: |
        echo $! > pid.txt

    - name: Main steps
      run: |
        echo "I am a step in a job"
