name: Call Common
on:
  push:
    branches:
      - main
jobs:
  Trigger-Build-in-DemoGHAction:
    uses: avinash221988/DemoGHActions/.github/workflows/docker-build.yml@main
    with:
      imageName: "tenant2image"