name: Call Common
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [ opened, synchronize]

jobs:
  Trigger-Build-in-DemoGHAction:
    uses: avinash221988/coreDemo/.github/workflows/docker-build.yml@main
    with:
      imageName: "tenant2image"
      TEST_VAR: ${{ vars.TEST_VAR }}
