name: CallCoreDemo
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [ opened, synchronize]
jobs:
  Writing-files:
    runs-on: ubuntu-latest
    steps:
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT" >> /tmp/GHContext.txt

     - name: Dump job context
       env:
          JOB_CONTEXT: ${{ toJson(job) }}
       run: |
          mkdir /tmp/job
          echo "$JOB_CONTEXT"  >> /tmp/job/jobdump.txt

     - name: Check ARchive paths
       run: |
            mkdir /tmp/archive
            echo "${{ inputs.PATHS }}" >> /tmp/archive/path.txt
    
     - name: Archive artifacts
       uses: actions/upload-artifact@v4
       with:
        name: tenant2_arts
        path: |
          /tmp/GHContext.txt
          /tmp/job/jobdump.txt
          /tmp/archive/path.txt
       
  Trigger-Build-in-DemoGHAction:
    uses: avinash221988/coreDemo/.github/workflows/docker-build.yml@main
    with:
      TEST_VAR: ${{ vars.TEST_VAR }}
      PATHS: |
        /tmp/GHContext.txt
        /tmp/job/jobdump.txt
        /tmp/archive/path.txt
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
      
      
