name: CallCoreDemo
on:
  push:
    branches:
      - main
  pull_request_target:
    types: [ opened, synchronize]
jobs:
  Writing-files:
    runs-on: ubuntu-latest
    steps:
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
       run: |
         mkdir -p $GITHUB_WORKSPACE/WF_Files
         echo "$GITHUB_CONTEXT" >> $GITHUB_WORKSPACE/WF_Files/GHContext.txt

     - name: Dump job context
       env:
          JOB_CONTEXT: ${{ toJson(job) }}
       run: |
          mkdir -p $GITHUB_WORKSPACE/WF_Files/job
          echo "$JOB_CONTEXT"  >> $GITHUB_WORKSPACE/WF_Files/job/jobdump.txt

     - name: Check ARchive paths
       run: |
            mkdir -p $GITHUB_WORKSPACE/WF_Files/archive
            echo "${{ inputs.PATHS }}" >> $GITHUB_WORKSPACE/WF_Files/archive/path.txt
    
     - name: Archive artifacts
       uses: actions/upload-artifact@v4
       with:
        name: tenant2_arts
        path: |
          $GITHUB_WORKSPACE/WF_Files/GHContext.txt
          $GITHUB_WORKSPACE/WF_Files/job/jobdump.txt
          $GITHUB_WORKSPACE/WF_Files/archive/path.txt
       
  Trigger-Build-in-DemoGHAction:
    uses: avinash221988/coreDemo/.github/workflows/docker-build.yml@main
    needs: Writing-files
    with:
      TEST_VAR: ${{ vars.TEST_VAR }}
      PATHS: |
        $GITHUB_WORKSPACE/WF_Files/GHContext.txt
        $GITHUB_WORKSPACE/WF_Files/job/jobdump.txt
        $GITHUB_WORKSPACE/WF_Files/archive/path.txt
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
